### PR TITLE
181 fix hydration errors

### LINKED ISSUE #181: Hydration errors
Experiencing various hydration error when refreshing the page.  This happens when logged in using Alby.

hydration-error1
hydration-error2
hydration-error3

### PR DESCRIPTION
**Pull request by e-roy**
### What does it do? Why?

This closes #181

### QA

This adds an extra hook `useIsMounted` which is a conditional to show the contents inside the `<NostrProvider />` on the `RootLayout`.   Let me know if you see anything wrong with this method.

### Review

- All GHA are success
- Use https://ui.shadcn.com/docs often as possible
- If Vercel build fails, run `yarn build` locally to get the same errors
      more to come...

### CODE REVIEW

**Comment by cypherhoodlum** [comment]
This can't be merged fast enough :smile:

**Comment by PeerRich** [comment]
i am not familiar with useIsMounted and its implications

**Comment by e-roy** [comment]
> i am not familiar with useIsMounted and its implications

in this context, simplest way to put it, when the layout renders, render what is inside.

or at least that's how I interpreted it.  it's common to do something like this with web3 apps

**Comment by e-roy** [comment]
to add more info to this, there is a react hook library for web3 wallets that suggest a similar solution for injected wallets.

[https://github.com/wagmi-dev/wagmi/issues/28#issuecomment-1005160238](https://github.com/wagmi-dev/wagmi/issues/28#issuecomment-1005160238)

**Review by PeerRich — APPROVED** [review]
approved lets see if it works 👌

**Pull request merged**
