### PR TITLE
move to next.js app directory 

### PR DESCRIPTION
**Pull request by brycedev**
- configures experimental app directory (not stable, but far along enough in my testing for what we're looking to do)
- setup routing for / , /entity/, and /entity/repo

### CODE REVIEW

**Comment by brycedev** [comment]
image

**Comment by PeerRich** [comment]
ouuh i like trying out the new /app with this repo

**Comment by PeerRich** [comment]
also @brycedev added you to core contributors, that way you can create branches in here vs forking

**Comment by brycedev** [comment]
> also @brycedev added you to core contributors, that way you can create branches in here vs forking

groovy. thank you 🫡

**Comment by PeerRich** [comment]
fyi: merge conflict. but should be fine to merge after!

**Pull request closed without merging**
