### PR TITLE
Fix responsive layout and Avatar UI

### PR DESCRIPTION
**Pull request by pierresisson**
### What does it do? Why?

- Fix issue with avatar size
before:
image
after:
image

- Remove min-width on main layout
- Fix dropdown signin
image

### QA

👉🏻 Check if Avatar and layout are not broken anymore

### Good To Know
related to https://github.com/NostrGit/NostrGit/issues/141

### Review

- [ ] All GHA are success
- [ ] Use https://ui.shadcn.com/docs often as possible
      more to come...

### CODE REVIEW

**Comment by pierresisson** [comment]
@cypherhoodlum i know you worked on the signin button, can you tell me if my pull request is ok for you ?

**Comment by PeerRich** [comment]
wanna address this too while you are at it? https://github.com/NostrGit/NostrGit/issues/138

**Comment by cypherhoodlum** [comment]
As @PeerRich said, it would be better to have a separate Sign in button. The current dropdown adds an unnecessary click. Sign out could instead be a dropdown, so we can use the code we have now for that.

**Comment by PeerRich** [comment]
yeah quite trivial:

`loggedIn ? <Dropdown/> : <Button>Sign In</Button>`

**Comment by pierresisson** [comment]
@cypherhoodlum i did not change the default settings that but i can add this if you want :)

**Pull request merged**
