### PR TITLE
clean up css on /issues and /pulls pages

### LINKED ISSUE #177: Clean up /issues and /pull pages mobile
tighten up consistency for mobile on `/issues` and `/pull` pages

issues-mobile
`/issues` page

mobile-pulls
`/pulls` page

### PR DESCRIPTION
**Pull request by e-roy**
### What does it do? Why?

closes #177 

### Review

- All GHA are success
- Use https://ui.shadcn.com/docs often as possible
- If Vercel build fails, run `yarn build` locally to get the same errors
      more to come...

### CODE REVIEW

**Comment by cypherhoodlum** [comment]
A gentle reminder to start the branch name with the related issue number if an issue exists :heart:

**Review by cypherhoodlum — APPROVED** [review]
LGTM :+1:

**Comment by e-roy** [comment]
> A gentle reminder to start the branch name with the related issue number if an issue exists ❤️

thank you!  I have some bad habits, so I do appreciate the help and reminders 🙏

**Comment by cypherhoodlum** [comment]
We all do :smile: but we can all learn from each other :+1:

**Pull request merged**
