### PR TITLE
Add some core stuff

### PR DESCRIPTION
**Pull request by pierresisson**
### What does it do? Why?
- Add prettier and eslint github as actions
- Add eslint in `scripts`
- run `npm run prettier` and `npm run eslint`
- moving `pull_request_template.md` in `root` directory
- add `husky` and add two pre commits : `prettier` and `eslint`

### CODE REVIEW

**Comment by brycedev** [comment]
maybe we could configure prettier as a pre-commit hook so unformatted code never reaches the repo

**Comment by pierresisson** [comment]
@brycedev good idea, husky ?

**Comment by pierresisson** [comment]
@brycedev done

**Comment by pierresisson** [comment]
what do you think about it @PeerRich

**Review by brycedev — APPROVED** [review]
nice 👍

**Comment by pierresisson** [comment]
@brycedev adding eslint too

**Pull request merged**
