### PR TITLE
Subtle design improvements in sign in

### PR DESCRIPTION
**Pull request by cypherhoodlum**
### What does it do? Why?

Fixes some subtle design issues on the sign in page:
👉🏻 &nbsp; I think Sign in link should be under everything else as is standard (Create one here).
👉🏻 &nbsp; Added the name Alby explicitly
👉🏻 &nbsp; What are these? link for new users who don't know what npubs, nsecs etc. are 
👉🏻 &nbsp; Point users who don't know about nostr to https://nostr.how

Before:
Screenshot from 2023-03-08 20-15-02

After:
Screenshot from 2023-03-08 21-27-55

### QA

👉🏻 &nbsp; Check that all links work.

### Review

- [x] All GHA are success
- [x] Use https://ui.shadcn.com/docs often as possible
      more to come...

### CODE REVIEW

**Comment by cypherhoodlum** [comment]
#128 related?

**Comment by PeerRich** [comment]
also, is this specifically alby or does every extension work? because nostore is also getting more common on iOS Safari.

if its generic and not alby-specific we could do: "Sign in with extension" as a full width button

**Comment by cypherhoodlum** [comment]
Let's aim for broader extension login imo.

**Comment by cypherhoodlum** [comment]
Latest design:
Screenshot from 2023-03-08 22-33-40

**Comment by PeerRich** [comment]
better, but lets take the 

<`Puzzle />` icon from lucide

CleanShot 2023-03-08 at 21 43 09@2x

**Comment by cypherhoodlum** [comment]
Screenshot from 2023-03-08 22-51-19

**Comment by pierresisson** [comment]
@cypherhoodlum eslint is fixed here https://github.com/NostrGit/NostrGit/issues/128

**Review by PeerRich — APPROVED** [review]

**Comment by cypherhoodlum** [comment]
As @PeerRich said, it would be better to have a separate Sign in button. The current dropdown adds an unnecessary click. Sign out could instead be a dropdown, so we can use the code we have now for that.

**Pull request merged**
