### PR TITLE
Add mobile layout

### PR DESCRIPTION
**Pull request by pierresisson**
### What does it do ? Why ?
Add a mobile layout and work as mobile first.
Meaning we have to think and write for a mobile view first and then others devices.

Example: `<div className="grid grid-cols-4 gap-6 lg:grid-cols-2">`

Steps :
- Fix global grid on mobile
- Fix aside width
- Convert `Tabs` to `Link`

### QA
Check if elements fit in mobile

### CODE REVIEW

**Comment by PeerRich** [comment]
just merged some minor things in a different PR. will wait for your work

**Comment by pierresisson** [comment]
@PeerRich ok, rebasing

**Comment by pierresisson** [comment]
@PeerRich how do you want to merge ? step by step ? tab by tab ?

**Comment by pierresisson** [comment]
@PeerRich maybe we should merge now? i don't know how you want to process

**Comment by pierresisson** [comment]
ooops, forget to add dropdown menu on mobile

**Comment by PeerRich** [comment]
can merge after conflicts resolved

we just merged the new /app dir

**Comment by pierresisson** [comment]
conflicts resolved, lets merge

**Comment by pierresisson** [comment]
@PeerRich i can't access to the vercel's logs failure?

**Pull request closed without merging**
