### PR TITLE
Add prettier order

### PR DESCRIPTION
**Pull request by pierresisson**
### What does it do ? Why ?
- Add prettier order to sort `imports`
- Add `prettierignore`

### CODE REVIEW

**Comment by PeerRich** [comment]
can we also add the tailwind css sorter? https://tailwindcss.com/blog/automatic-class-sorting-with-prettier

**Review by cypherhoodlum — APPROVED** [review]
Very neat. :100:  
While you're at it, could I ask you @pierresisson to also write a few lines of instructions on the steps needed to ensure the code keeps formatted and sorted out with the prettier config? Just a simple section to the Coding conventions [here](https://github.com/NostrGit/NostrGit/blob/main/documentation/development/contributing.md)? It could be done to the same branch to be efficient.

**Review by brycedev — APPROVED** [review]

**Comment by pierresisson** [comment]
arf @PeerRich i was adding documentation ahah, doing this in another PR

**Comment by cypherhoodlum** [comment]
Ah, should have requested changed instead of approving, sorry. Code still good :100:

**Pull request merged**
