### PR TITLE
feat: basic  /pulls page ui

### PR DESCRIPTION
**Pull request by e-roy**
### What does it do? Why?

👉🏻 &nbsp;Please add a description of what this `pull request` does.
This PR adds a basic UI for the `/pulls` page #154 

### QA

👉🏻 &nbsp;Please add what you think the reviewer has to test.

### Review
basic-pulls-page

- [x] All GHA are success
- [x] Use https://ui.shadcn.com/docs often as possible
      more to come...

### CODE REVIEW

**Comment by e-roy** [comment]
This PR does fails when I run `yarn build` locally before and after these changes.

In the '/header.tsx` I only changed the href in the navigation, the rest of the changes happened on auto save.  Let me know if I need to undo these changes

**Comment by pierresisson** [comment]
hi @e-roy why did you remove my factorize ?

https://github.com/NostrGit/NostrGit/commit/5bdf0232c46f3f89bffec3ea8a74a63657fb9ce8
it did not work?

**Comment by PeerRich** [comment]
can we move this into the subpage: 

https://nostrgit.com/nostr-protocol/nostr/pull

**Comment by e-roy** [comment]
> hi @e-roy why did you remove my factorize ?
> 
> [5bdf023](https://github.com/NostrGit/NostrGit/commit/5bdf0232c46f3f89bffec3ea8a74a63657fb9ce8) it did not work?
> 

It didn't work because `issueType` and `issueStatus` would never be able to change in this conditional.   does that make sense?  if there was a way to pass an arg into these functions and use the arg in the conditional, otherwise separate functions seemed like a better approach.  

Let me know if you see something different 🙂

**Comment by e-roy** [comment]
> can we move this into the subpage:
> 
> https://nostrgit.com/nostr-protocol/nostr/pull

this is actually built for the User's pull request from the top bar navigation, like the issues I previously did.   where I started with #61, but there was something wrong with my branch so #126 was created

**Comment by pierresisson** [comment]
> > hi @e-roy why did you remove my factorize ?
> > [5bdf023](https://github.com/NostrGit/NostrGit/commit/5bdf0232c46f3f89bffec3ea8a74a63657fb9ce8) it did not work?
> 
> It didn't work because `issueType` and `issueStatus` would never be able to change in this conditional. does that make sense? if there was a way to pass an arg into these functions and use the arg in the conditional, otherwise separate functions seemed like a better approach.
> 
> Let me know if you see something different 🙂

y i agree, btw it was just to create a  `useCallback` before the the return and not a jsx callback
thank you!

**Comment by e-roy** [comment]
> 
> y i agree, btw it was just to create a `useCallback` before the the return and not a jsx callback thank you!

yes! once I saw your example I understood what you were referring to and it helped me look into and understand why it was a bad practice 🙏 thank you, I appreciate it!  😃

**Review by cypherhoodlum — APPROVED** [review]
LGTM :+1:  Great job @e-roy!

**Pull request merged**
