### PR TITLE
added nip-5

### PR DESCRIPTION
**Pull request by PeerRich**
### What does it do? Why?

👉🏻 &nbsp; added nip5 for the nostr account (https://no.str.bio/nostrgit) and for core contributors

Feel free to suggest your own NIP-5 identifiers in this PR with the suggest feature of github

### CODE REVIEW

**Comment by pierresisson** [comment]
hummm Prettier should not run here 🤔

**Comment by PeerRich** [comment]
> hummm Prettier should not run here 🤔

wdym?

**Comment by pierresisson** [comment]
> > hummm Prettier should not run here 🤔
> 
> wdym?

image

**Comment by pierresisson** [comment]
@PeerRich oh yeah it is a `.json`, thats why
we should prettierise all file in the config! on it

**Review by pierresisson — APPROVED** [review]
LGTM 🚀

**Comment by cypherhoodlum** [comment]
Ah, just pushed an updated name for myself. Let's see what happens.

**Pull request merged**
