### PR TITLE
Page for global settings

### LINKED ISSUE #180: /settings UI starting point.
Tentative UI for global /settings. Not to be confused with repository settings.

### PR DESCRIPTION
**Pull request by cypherhoodlum**
### What does it do? Why?

Closes #180.

Tentative UI for global settings page on /settings.
Screenshot from 2023-03-12 22-32-00

### Review

- All GHA are success
- Use https://ui.shadcn.com/docs often as possible
- If Vercel build fails, run `yarn build` locally to get the same errors
      more to come...

### CODE REVIEW

**Comment by PeerRich** [comment]
shit we'Re working on the same ticket

**Comment by PeerRich** [comment]
my PR: https://github.com/NostrGit/NostrGit/pull/182

**Comment by PeerRich** [comment]
my PR is a bit more advanced, should we use my branch instead?

**Comment by cypherhoodlum** [comment]
Closed as duplicate to #182.

**Comment by cypherhoodlum** [comment]
> my PR is a bit more advanced, should we use my branch instead?

Fortunately I didn't use too much time on this :smile: Let's always self-assign issues to make it clearer who's working on what, tho.

**Pull request closed without merging**
