### PR TITLE
frontend improvements

### PR DESCRIPTION
**Pull request by PeerRich**
- fixed a ton of padding and sizing
- new `<SearchBar>`
- new `<Logo>`
- added Logo to mobile heading
- added notification icon

### CODE REVIEW

**Review by cypherhoodlum — CHANGES_REQUESTED** [review]
The sign in/up buttons are broken in the navbar:
Screenshot from 2023-03-12 15-26-34

And in the mobile navbar the same buttons could be padded or somehow separated from the bottom border of the menu. They look a little odd to me.
Screenshot from 2023-03-12 15-31-21

Is there a reason for the changes to yarn.lock?

Otherwise everything looks good to my eye :+1: I like what you did with the sign up!

**Comment by PeerRich** [comment]
> Is there a reason for the changes to yarn.lock?

i think this comes from a different branch. should be save to overwrite

**Comment by PeerRich** [comment]
fixed buttons, didnt test on smaller screens

**Review by cypherhoodlum — APPROVED** [review]
LGTM :+1:

**Pull request merged**
